name: absensi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  clipboard: ^2.0.2
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.2
  connectivity_plus: ^7.0.0
  data_table_2: ^2.6.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.2.1
  flutter_native_splash: ^2.4.6
  flutter_typeahead: ^5.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  html: ^0.15.6
  http: ^1.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800
