// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8dD82XgDZmzyJSvXhldg8puMn0HPu18',
    appId: '1:236549658227:web:a5d3ab8fdfb00cd3bc7c06',
    messagingSenderId: '236549658227',
    projectId: 'absensi0978flutter',
    authDomain: 'absensi0978flutter.firebaseapp.com',
    storageBucket: 'absensi0978flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtt9v2liIU02C762OcYa83UwFAjXwEhI',
    appId: '1:236549658227:android:6c8329ec9b3b60a1bc7c06',
    messagingSenderId: '236549658227',
    projectId: 'absensi0978flutter',
    storageBucket: 'absensi0978flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunpqR_NH6MxHyUfMcx4iIM1wjZ16Puec',
    appId: '1:236549658227:ios:3b8333a49efd4855bc7c06',
    messagingSenderId: '236549658227',
    projectId: 'absensi0978flutter',
    storageBucket: 'absensi0978flutter.firebasestorage.app',
    iosBundleId: 'com.example.absensi',
  );

}